# 第一章 向量、矩阵和数组

In [13]:
import numpy as np
from scipy import sparse 

## 1.1 创建一个向量

创建一个行向量

In [2]:
vector_row = np.array([1,2,3])
vector_row

array([1, 2, 3])

创建一个列向量

In [4]:
vector_column = np.array([[1],[2],[3]])
vector_column

array([[1],
       [2],
       [3]])

## 1.2 创建一个矩阵

使用numpy数组创建矩阵

In [29]:
matrix = np.array([[1,2],[1,2],[1,2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

使用numpy矩阵对象创建矩阵（不推荐）

In [28]:
matrix_object = np.matrix([[1,2],[1,2],[1,2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

## 1.3 创建稀疏矩阵

In [9]:
matrix_compressed = np.array([
    [0, 0],
    [0, 1],
    [0, 3]
])
matrix_compressed

array([[0, 0],
       [0, 1],
       [0, 3]])

In [15]:
matrix_sparse_csr = sparse.csr_matrix(matrix_compressed)
print(matrix_sparse_csr)

  (1, 1)	1
  (2, 1)	3


## 1.4 选择元素

In [18]:
vector_element = vector_row[0] 
vector_element

1

In [31]:
# 索引的方式
matrix_element = matrix[1,0]
# 切片的方式
matrix_elements = matrix[:, 0:1]
matrix_element,matrix_elements

(1, array([[1],
        [1],
        [1]]))

## 1.5 展示矩阵的属性

In [32]:
# 形状
matrix.shape

(3, 2)

In [33]:
# 大小
matrix.size

6

In [34]:
# 维度
matrix.ndim

2

## 1.6 对多个元素同时使用操作

In [37]:
matrix_6 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# 创建向量化函数
vectorized_add = np.vectorize(lambda i : i+100)
matrix_6_all = vectorized_add(matrix_6)
matrix_6_part = vectorized_add(matrix_6[0, :])
matrix_6_all, matrix_6_part

(array([[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]]), array([101, 102, 103]))

使用NumPy广播特性

In [39]:
matrix_6_broadcast_1 = matrix_6 + np.array([1,2,3])
matrix_6_broadcast_1

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
# 下面不符合广播规则，无法计算
matrix_6_broadcast_2 = matrix_6 + np.array([1,2,3,4])
matrix_6_broadcast_2 = matrix_6 + np.array([1,2])
matrix_6_broadcast_2

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

## 1.7 最大最小元素

In [42]:
matrix_7 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
all_min = np.min(matrix_7)
all_max = np.max(matrix_7)
row_min = np.min(matrix_7, axis=1)
column_max = np.max(matrix_7, axis=0)
all_min,all_max, row_min, column_max

(1, 9, array([1, 4, 7]), array([7, 8, 9]))

## 1.8 平均值、方差和标准差

In [43]:
matrix_8 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
mean = np.mean(matrix_8)
var = np.var(matrix_8)
std = np.std(matrix_8)
mean,var,std

(5.0, 6.666666666666667, 2.581988897471611)